customerLogin="//a[normalize-space()='Customer Login']"
usernamelocator="//input[@id='input-email']"
usernamevalue="demouser@demo.com"
passwordlocator="input-password"
passwordvalue="demopass"
loginbtn="//input[@value='Login']" 
logoutbtn="//a[@class='list-group-item logu']"
yahoo="https://www.yahoo.com/"
google="https://www.google.com/"
msn="https://www.msn.com/en-in"
bing="https://www.bing.com/"